### PR TITLE
KOGITO-7944 Fix `:knative_eventing_doc_url:` extra '/' and broken link

### PR DESCRIPTION
**Pull request by zdrapela**
**JIRA:**
https://issues.redhat.com/browse/KOGITO-7944

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] The nav.adoc file has a link to this guide in the proper category
- [x] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to setup automatic cherry-pick to another branch ?
</summary>

The cherry-pick action allows to setup automatic cherry-pick from `main` to a specific branch.

To allow it, you will need to add the corresponding label with pattern: `backport-{RELEASE_BRANCH}`.  
For example, if a backport to branch `1.26.x` is needed, then the label should be `backport-1.26.x`.

Once the PR is merged, the action will retrieve the commit and cherry-pick it to the desired branch.

*NOTE: You can still add label after the merge and it should still be cherry-picked.*
</details>

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by zdrapela** [comment]
> @zdrapela does it need a backport to 1.27.x ?

It was not so severe, only one link was broken and others were working through an automatic redirect from '//' to '/'. I don't think it is needed, but I am not sure what is the best practice here.

**Comment by domhanak** [comment]
:+1: for backporting @zdrapela just cherry-pick the commit to the branch and open a separate PR and thanks for the fix

**Comment by radtriste** [comment]
> +1 for backporting @zdrapela just cherry-pick the commit to the branch and open a separate PR and thanks for the fix

@domhanak @zdrapela for cherry-picking on kogito-docs, we just need to set the label `backport-1.27.x` and GHA will create the cherry-pick to 1.27.x once PR is closed

**Comment by domhanak** [comment]
@radtriste nice, didn't know thanks for the tip

**Comment by zdrapela** [comment]
@radtriste cool, thanks!

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
