### PR TITLE
[1.42.x backport] KOGITO-9463: Create a new guide describing the Job Services Quarkus Extensions (#408)

### PR DESCRIPTION
**Pull request by wmedvede**
* KOGITO-9463: Create a new guide describing the Job Services Quarkus Extensions

* Code review suggestions I

* Code review suggestions II

* Code review suggestions III

* Code review suggestions IV

* Code review suggestions V

**JIRA:**

**Description:**

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [X] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [X] The nav.adoc file has a link to this guide in the proper category
- [X] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
@radtriste @ricardozanini Guys, this is the backport of the jobs-service documentation in the **1.42.x** branch, it was my fault to not mark it to be backported  at the time we merged the documentation in master :angry:.

the peer backport into 1.40.x is here https://github.com/kiegroup/kogito-docs/pull/444
the peer backport into 1.40.x-prod is here https://github.com/kiegroup/kogito-docs/pull/445

**Comment by radtriste** [comment]
> @radtriste @ricardozanini Guys, this is the backport of the jobs-service documentation in the **1.42.x** branch, it was my fault to not mark it to be backported at the time we merged the documentation in master angry.
> 
> the peer backport into 1.40.x is here #444 the peer backport into 1.40.x-prod is here #445

FYI, you can still set the label after the merge and the backport will happen ;)

**Comment by wmedvede** [comment]
> > @radtriste @ricardozanini Guys, this is the backport of the jobs-service documentation in the **1.42.x** branch, it was my fault to not mark it to be backported at the time we merged the documentation in master angry.
> > the peer backport into 1.40.x is here #444 the peer backport into 1.40.x-prod is here #445
> 
> FYI, you can still set the label after the merge and the backport will happen ;)

Aha!, good to know that, but please don't add them for this particular case, since I had to resolve some merge conflicts manually to backport, since many things happened in the middle since my initial commit, and other commits went before.
But yeah, thanks for the info!

**Comment by radtriste** [comment]
sure no problem :) cc @ricardozanini

**Review by ricardozanini — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by wmedvede** [comment]
Guys @radtriste @ricardozanini , I'll merge this PR to be sure we don't forget it and fall into the same situation again. B
Note that:
1) I'll be on PTO for some weeks.
2) It is a backport that is simply adding content that was already reviewed in the original PR, so we don't need for more greens.

**Pull request merged**
