### PR TITLE
KOGITO-7636 SW configuration properties guide

### PR DESCRIPTION
**Pull request by cristianonicolai**
The goal here is to simply describe the current configuration properties we have that are relevant to SW.

In case we want to rename, lets create JIRA to track it.

### CODE REVIEW

**Review by fjtirado — COMMENTED** [review]
@cristianonicolai nice work. 
Should not we add a brief description of each property base on the javadod already present in the config bean?

**Comment by ricardozanini** [comment]
> @cristianonicolai nice work. Should not we add a brief description of each property base on the javadod already present in the config bean?

This guide ideally should be generated based on the Java code, so we would make it up to date with the code changes.

**Review by ricardozanini — COMMENTED** [review]
@cristianonicolai, I agree with @fjtirado. Can you add a description for these configs?

**Comment by cristianonicolai** [comment]
@ricardozanini @fjtirado added description

**Review by tiagodolphine — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]
I think it's fine adding this table, but I'm missing context for these properties. In the future, we can link a guide to each property so the reader will have more context.

**Review by fjtirado — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@hmanwani-rh ready for your review

**Comment by hmanwani-rh** [comment]
Merging this PR to create a patch PR with doc improvements.

**Pull request merged**
