### PR TITLE
Docs Patch PR for KOGITO-8078: Document adding custom type through addon

### PR DESCRIPTION
**Pull request by kaldesai**
**JIRA:[KOGITO-8078](https://issues.redhat.com/browse/KOGITO-8078)**

**Description:** I reviewed the content for the **Custom function types** section and added my suggestions. Please take a look and reach out to me if you have any questions.

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category
- [ ] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to setup automatic cherry-pick to another branch ?
</summary>

The cherry-pick action allows to setup automatic cherry-pick from `main` to a specific branch.

To allow it, you will need to add the corresponding label with pattern: `backport-{RELEASE_BRANCH}`.  
For example, if a backport to branch `1.26.x` is needed, then the label should be `backport-1.26.x`.

Once the PR is merged, the action will retrieve the commit and cherry-pick it to the desired branch.

*NOTE: You can still add label after the merge and it should still be cherry-picked.*
</details>

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by fjtirado — APPROVED** [review]

**Comment by fjtirado** [comment]
@kaldesai 
Can we add what  @MarianMacik was requesting

Basically, to add this to the Example of the RPC function Java implementation
```
 @Override
    public String type() {
        return "rpc";
    }
```
And rephrase  he parragrap below, from
_This example setups the name of the KogitoWorkItemHandler and adds a metadata key that extracts the name of the operation to perform in the legacy server from the Serverless workflow function definition._
to
This example setups the name of the KogitoWorkItemHandlerm adds a metadata key that extracts the name of the operation to perform in the legacy server from the Serverless workflow function definition, and declare that the custom type is named "rpc"

**Comment by kaldesai** [comment]
> @kaldesai Can we add what @MarianMacik was requesting before the other PR was merged?
> 
> Basically, to add this to the Example of the RPC function Java implementation
> 
> ```
>  @Override
>     public String type() {
>         return "rpc";
>     }
> ```
> 
> so it looks like this
> 
> ```
> 
> import static org.kie.kogito.examples.sw.custom.RPCCustomWorkItemHandler.NAME;
> import static org.kie.kogito.examples.sw.custom.RPCCustomWorkItemHandler.OPERATION;
> 
> public class RPCCustomTypeHandler extends WorkItemTypeHandler{
> 
> 
>     @Override
>     public String type() {
>         return "rpc";
>     }
> 
>     @Override
>     protected <T extends RuleFlowNodeContainerFactory<T, ?>> WorkItemNodeFactory<T> fillWorkItemHandler(Workflow workflow,
>                                                                                                         ParserContext context,
>                                                                                                         WorkItemNodeFactory<T> node,
>                                                                                                         FunctionDefinition functionDef) {
>         return node.workName(NAME).metaData(OPERATION, trimCustomOperation(functionDef));
>     }
> }
> ```
> 
> And rephrase the paragraph below, from `_This example setups the name of the KogitoWorkItemHandler and adds a metadata key that extracts the name of the operation to perform in the legacy server from the Serverless workflow function definition._ to _This example setups the name of the KogitoWorkItemHandler, adds a metadata key with the name of the remote operation (extracted from the Serverless workflow function definition operation property), and declare that the custom type is named "rpc"_

@fjtirado, Sure, I will add this to the content. Thank you for pointing it out. :)

**Review by ricardozanini — APPROVED** [review]
Just minor suggestions; feel free to ignore them.

**Comment by kaldesai** [comment]
@fjtirado and @ricardozanini, I have incorporated your suggestions. Thank you for reviewing!

**Comment by ricardozanini** [comment]
@kaldesai as soon as @MarianMacik approves it, we can merge.

**Comment by kaldesai** [comment]
> @kaldesai as soon as @MarianMacik approves it, we can merge.

@ricardozanini Done!! :)

**Review by MarianMacik — APPROVED** [review]
Thanks!

**Pull request merged**
