### PR TITLE
KOGITO-7417: Add switchable tabs in Antora

### PR DESCRIPTION
**Pull request by akumar074**
* Added tabsets extension
 * Changed navbar theme

How to create tabs in page:
```
[tabs]
====
Tab A::
+
[source,shell]
--
Contents of tab A.
--
Tab B::
+
[source,java]
--
Contents of tab B.
--
Tab C::
+
[source,c]
--
Contents of tab C.
--
====
```

**JIRA:**

**Description:**

Please make sure that your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Maybe we can edit @spolti and @hbelmiro guides to add the new tab feature in this same PR? wdyt? So we can see how that works and show an example to future writers. 🤗

**Comment by akumar074** [comment]
Yes that would be great! I'll add the syntax in  contribution doc also. :)

**Review by spolti — APPROVED** [review]

**Review by krisv — APPROVED** [review]

**Comment by akumar074** [comment]
Hi @rsynek 
I added you for review in this PR because it is related to the Antora extension and we would like your opinion on this implementation. Please take a look.
Thanks.

**Review by rsynek — APPROVED** [review]
LGTM.

**Pull request merged**
