### PR TITLE
[1.32.x] KOGITO-7676: Added Flyway to release notes

### PR DESCRIPTION
**Pull request by akumar074**
**JIRA:** [KOGITO-7676](https://issues.redhat.com/browse/KOGITO-7676)

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category
- [ ] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to setup automatic cherry-pick to another branch ?
</summary>

The cherry-pick action allows to setup automatic cherry-pick from `main` to a specific branch.

To allow it, you will need to add the corresponding label with pattern: `backport-{RELEASE_BRANCH}`.  
For example, if a backport to branch `1.26.x` is needed, then the label should be `backport-1.26.x`.

Once the PR is merged, the action will retrieve the commit and cherry-pick it to the desired branch.

*NOTE: You can still add label after the merge and it should still be cherry-picked.*
</details>

### CODE REVIEW

**Comment by radtriste** [comment]
@akumar074 Please do this change only on branch 1.32.xm which will come today or tomorrow

**Comment by akumar074** [comment]
Thanks @radtriste , I converted the PR to draft and will change the base to 1.32.x when available.

**Review by cristianonicolai — APPROVED** [review]

**Comment by radtriste** [comment]
@akumar074 you can change the base branch

**Review by kaldesai — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Comment by akumar074** [comment]
@ricardozanini Can we merge this one?

**Review by ricardozanini — APPROVED** [review]

**Comment by akumar074** [comment]
@ricardozanini @radtriste Can we merge this?

**Pull request merged**
