### PR TITLE
Fixed/updated example url

### PR DESCRIPTION
**Pull request by hbelmiro**
Fixes and updates the example URL in the Getting Started guide

### CODE REVIEW

**Review by ricardozanini — COMMENTED** [review]
@hbelmiro many thanks! Is this the only guide with the wrong links?

**Review by spolti — APPROVED** [review]

**Comment by hbelmiro** [comment]
> @hbelmiro many thanks! Is this the only guide with the wrong links?

Of the ones I created, yes.

**Review by krisv — APPROVED** [review]

**Comment by ricardozanini** [comment]
> > @hbelmiro many thanks! Is this the only guide with the wrong links?
> 
> Of the ones I created, yes.

asked because we could update every other guide with a simple find and replace. Can you do it in this PR, please?

**Comment by hbelmiro** [comment]
> > > @hbelmiro many thanks! Is this the only guide with the wrong links?
> > 
> > 
> > Of the ones I created, yes.
> 
> asked because we could update every other guide with a simple find and replace. Can you do it in this PR, please?

Sure.

**Review by ricardozanini — APPROVED** [review]
Thank you!!

**Pull request merged**
