### PR TITLE
Synchronize main branch with Apache

### PR DESCRIPTION
**Pull request by domhanak**

### CODE REVIEW

**Comment by domhanak** [comment]
I guess I need to revert the CI updates to do this

**Comment by rgdoliveira** [comment]
> I guess I need to revert the CI updates to do this

For the projects we productized I've been ignoring most of the changes in .ci and .jenkins as some of them are only related to Apache. But for kogito-docs I dont know much the context, but maybe we should follow this same idea? But let's see what others think.

**Comment by ricardozanini** [comment]
Do we need midstream for this repo? 🤔

**Comment by domhanak** [comment]
@ricardozanini Good question, I was trying to figure out a process to have midstream for doc syncing but didnt figure it out yet. This PR is result of the backport happening now :D

**Comment by ricardozanini** [comment]
@domhanak @rgdoliveira I think we don't need it. The openshift-knative is our midstream. And once we migrate to OpenShift Docs, that will be an entire new process/architecture.

**Comment by domhanak** [comment]
Closing.

**Pull request closed without merging**
